### ISSUE TITLE
Some test failures

### ISSUE THREAD

**Issue by alexploner** [bulik/ldsc#36]
A few formal tests suggested in the [wiki](https://github.com/bulik/ldsc/wiki/Tests) fail on my Windows machine, even with a factory-fresh python- and ldsc-installation, see output below.

ldsc still seems to be working fine (e.g. the tutorial schizophrenia/bipolar correlation), but it's a bit disconcerting. 

Windows 7
Python 2.7.10 :: Anaconda 2.3.0 (64-bit)
ldsc v1.0.0 commit 34394e8977119bcad899cc13f2e255d89c45997a (August 3)

Test results:
```
$ nosetests -A 'not slow'
..............................................................F.F...............
.........................................................
======================================================================
FAIL: test_n_cas_con_flag (test_munge_sumstats.test_process_n)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\xxxxxx\ldsc\test\test_munge_sumstats.py", line 104, in test_n_c
as_con_flag
    assert_series_equal(dat.N, self.N_const)
  File "c:\Users\xxxxxx\AppData\Local\Continuum\Anaconda\lib\site-packages\panda
s\util\testing.py", line 701, in assert_series_equal
    assert_attr_equal('name', left, right)
  File "c:\Users\xxxxxx\AppData\Local\Continuum\Anaconda\lib\site-packages\panda
s\util\testing.py", line 552, in assert_attr_equal
    assert_equal(left_attr,right_attr,"attr is not equal [{0}]" .format(attr))
  File "c:\Users\xxxxxx\AppData\Local\Continuum\Anaconda\lib\site-packages\panda
s\util\testing.py", line 533, in assert_equal
    assert a == b, "%s: %r != %r" % (msg.format(a,b), a, b)
AssertionError: attr is not equal [name]: 'N' != None

======================================================================
FAIL: test_n_flag (test_munge_sumstats.test_process_n)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\xxxxxx\ldsc\test\test_munge_sumstats.py", line 97, in test_n_fl
ag
    assert_series_equal(dat.N, self.N_const)
  File "c:\Users\xxxxxx\AppData\Local\Continuum\Anaconda\lib\site-packages\panda
s\util\testing.py", line 701, in assert_series_equal
    assert_attr_equal('name', left, right)
  File "c:\Users\xxxxxx\AppData\Local\Continuum\Anaconda\lib\site-packages\panda
s\util\testing.py", line 552, in assert_attr_equal
    assert_equal(left_attr,right_attr,"attr is not equal [{0}]" .format(attr))
  File "c:\Users\xxxxxx\AppData\Local\Continuum\Anaconda\lib\site-packages\panda
s\util\testing.py", line 533, in assert_equal
    assert a == b, "%s: %r != %r" % (msg.format(a,b), a, b)
AssertionError: attr is not equal [name]: 'N' != None

----------------------------------------------------------------------
Ran 137 tests in 3.229s

FAILED (failures=2)




$ nosetests -A 'slow'
.........................F....
======================================================================
FAIL: test_sumstats.Test_RG_Statistical.test_hsq_int_se
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\xxxxxx\AppData\Local\Continuum\Anaconda\lib\site-packages\nose\
case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\Users\xxxxxx\ldsc\test\test_sumstats.py", line 274, in test_hsq_int_s
e
    map(t('intercept'), map(t('hsq2'), self.rg))), atol=0.1)
  File "c:\Users\xxxxxx\AppData\Local\Continuum\Anaconda\lib\site-packages\numpy
\testing\utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "c:\Users\xxxxxx\AppData\Local\Continuum\Anaconda\lib\site-packages\numpy
\testing\utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-07, atol=0.1

(mismatch 100.0%)
 x: array(0.5372853385973988)
 y: array(0.6539727418594192)

----------------------------------------------------------------------
Ran 30 tests in 43.639s

FAILED (failures=1)
```

**Comment by bulik** [comment]
Thanks for pointing this out. It looks like the errors were caused by a change to some of the test functions provided by pandas (`assert_series_equal` now checks for column name equality by default whereas it did not in previous versions of pandas). I've fixed this in the latest commit.

**Comment by jocen** [comment]
It seems the bug is still persistent in current version.

LDSC version from commit f7c3316d4cc4012afd26743f56052389dd512d9c (9/11/2016)

Systems tested (all 64 bit):

 System          | Inst.  | Python |  NumPy |  SciPy | Pandas
-----------------|--------|--------|--------|--------|--------
 Ubuntu 14.04LTS | OS repos  |  2.7.6 | 1.11.2 | 0.13.3 | 0.19.1
 Debian 8        | OS repos  |  2.7.9 |  1.8.2 | 0.14.0 | 0.17.1
 Ubuntu 14.04LTS | Anacondas 4.20 | 2.7.12 | 1.11.2 | 0.18.1 | 0.19.1

```
jo@jo-ThinkPad:/tmp/ldsc$ nosetests-2.7 -A 'slow'
.........................F....
======================================================================
FAIL: test_sumstats.Test_RG_Statistical.test_hsq_int_se
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/ldsc/test/test_sumstats.py", line 274, in test_hsq_int_se
    map(t('intercept'), map(t('hsq2'), self.rg))), atol=0.1)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1392, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 739, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0.1

(mismatch 100.0%)
 x: array(0.5372853385973988)
 y: array(0.6539727418594191)

----------------------------------------------------------------------
Ran 30 tests in 48.827s

FAILED (failures=1)
```

For the `not slow` tests:

```
jo@jo-ThinkPad:/tmp/ldsc$ nosetests -A 'not slow'
..........................................................................................................E............E..E.E............
======================================================================
ERROR: test_summary (test_regressions.Test_Hsq_2D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/ldsc/test/test_regressions.py", line 200, in test_summary
    self.chisq, self.ld, self.w_ld, self.N, self.M, n_blocks=3)
  File "/tmp/ldsc/ldscore/regressions.py", line 346, in __init__
    slow=slow, step1_ii=step1_ii, old_weights=old_weights)
  File "/tmp/ldsc/ldscore/regressions.py", line 213, in __init__
    x, yp, update_func, n_blocks, slow=slow, w=initial_w)
  File "/tmp/ldsc/ldscore/irwls.py", line 66, in __init__
    x, y, update_func, n_blocks, w, slow=slow, separators=separators)
  File "/tmp/ldsc/ldscore/irwls.py", line 127, in irwls
    x, y, n_blocks, separators=separators)
  File "/tmp/ldsc/ldscore/jackknife.py", line 309, in __init__
    self.est = self.block_values_to_est(xty, xtx)
  File "/tmp/ldsc/ldscore/jackknife.py", line 386, in block_values_to_est
    return np.linalg.solve(xtx, xty).reshape((1, p))
  File "/usr/local/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 384, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
  File "/usr/local/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 90, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
LinAlgError: Singular matrix

======================================================================
ERROR: test_h2_ref_ld (test_sumstats.Test_Estimate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/ldsc/test/test_sumstats.py", line 389, in test_h2_ref_ld
    x = s.estimate_h2(args, log)
  File "/tmp/ldsc/ldscore/sumstats.py", line 265, in estimate_h2
    args, log, args.h2)
  File "/tmp/ldsc/ldscore/sumstats.py", line 247, in _read_ld_sumstats
    sumstats = _merge_and_log(ref_ld, sumstats, 'reference panel LD', log)
  File "/tmp/ldsc/ldscore/sumstats.py", line 230, in _merge_and_log
    sumstats = smart_merge(ld, sumstats)
  File "/tmp/ldsc/ldscore/sumstats.py", line 69, in smart_merge
    if len(x) == len(y) and (x.SNP == y.SNP).all():
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/ops.py", line 812, in wrapper
    raise ValueError(msg)
ValueError: Can only compare identically-labeled Series objects
-------------------- >> begin captured stdout << ---------------------
Reading summary statistics from /tmp/ldsc/test/simulate_test/sumstats/555 ...
Read summary statistics for 1000 SNPs.
Reading reference panel LD Score from /tmp/ldsc/test/simulate_test/ldscore/twold_onefile[1-22] ...
Read reference panel LD Scores for 1000 SNPs.
Removing partitioned LD Scores with zero variance.
Reading regression weight LD Score from /tmp/ldsc/test/simulate_test/ldscore/w ...
Read regression weight LD Scores for 1000 SNPs.

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_rg_ref_ld (test_sumstats.Test_Estimate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/ldsc/test/test_sumstats.py", line 434, in test_rg_ref_ld
    x = s.estimate_rg(args, log)[0]
  File "/tmp/ldsc/ldscore/sumstats.py", line 336, in estimate_rg
    alleles=True, dropna=True)
  File "/tmp/ldsc/ldscore/sumstats.py", line 247, in _read_ld_sumstats
    sumstats = _merge_and_log(ref_ld, sumstats, 'reference panel LD', log)
  File "/tmp/ldsc/ldscore/sumstats.py", line 230, in _merge_and_log
    sumstats = smart_merge(ld, sumstats)
  File "/tmp/ldsc/ldscore/sumstats.py", line 69, in smart_merge
    if len(x) == len(y) and (x.SNP == y.SNP).all():
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/ops.py", line 812, in wrapper
    raise ValueError(msg)
ValueError: Can only compare identically-labeled Series objects
-------------------- >> begin captured stdout << ---------------------
Reading summary statistics from /tmp/ldsc/test/simulate_test/sumstats/1 ...
Read summary statistics for 1000 SNPs.
Reading reference panel LD Score from /tmp/ldsc/test/simulate_test/ldscore/twold_onefile[1-22] ...
Read reference panel LD Scores for 1000 SNPs.
Removing partitioned LD Scores with zero variance.
Reading regression weight LD Score from /tmp/ldsc/test/simulate_test/ldscore/w ...
Read regression weight LD Scores for 1000 SNPs.

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_twostep_rg (test_sumstats.Test_Estimate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/ldsc/test/test_sumstats.py", line 483, in test_twostep_rg
    x = s.estimate_rg(args, log)[0]
  File "/tmp/ldsc/ldscore/sumstats.py", line 336, in estimate_rg
    alleles=True, dropna=True)
  File "/tmp/ldsc/ldscore/sumstats.py", line 247, in _read_ld_sumstats
    sumstats = _merge_and_log(ref_ld, sumstats, 'reference panel LD', log)
  File "/tmp/ldsc/ldscore/sumstats.py", line 230, in _merge_and_log
    sumstats = smart_merge(ld, sumstats)
  File "/tmp/ldsc/ldscore/sumstats.py", line 69, in smart_merge
    if len(x) == len(y) and (x.SNP == y.SNP).all():
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/ops.py", line 812, in wrapper
    raise ValueError(msg)
ValueError: Can only compare identically-labeled Series objects
-------------------- >> begin captured stdout << ---------------------
Reading summary statistics from /tmp/ldsc/test/simulate_test/sumstats/1 ...
Read summary statistics for 1000 SNPs.
Reading reference panel LD Score from /tmp/ldsc/test/simulate_test/ldscore/oneld_onefile[1-22] ...
Read reference panel LD Scores for 1000 SNPs.
Removing partitioned LD Scores with zero variance.
Reading regression weight LD Score from /tmp/ldsc/test/simulate_test/ldscore/w ...
Read regression weight LD Scores for 1000 SNPs.

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 137 tests in 2.202s

FAILED (errors=4)
```
